#!/bin/bash
# mutterer [install|mutt|imap|smtp] [options...]

set -e -u

export MUTTERER_LIBS="${MUTTERER_LIBS-$(dirname "$0")/lib}"
export MUTTERER_SYSTEM_PRESETS="${MUTTERER_SYSTEM_PRESETS-$(dirname "$0")/presets}"

. "$MUTTERER_LIBS/m_common"
. "$MUTTERER_LIBS/m_installer"

case "${1-}" in
    install) make_config;;
    mutt)    shift; make_config_if_updated; mutt "$@";;
    imap)    shift; make_config_if_updated; offlineimap "$@";;
    smtp)    shift; make_config_if_updated; msmtp "$@";;
    *)       make_config_if_updated; mutt "$@";;
esac
