#!/bin/bash
# mutterer [install|mutt|imap|smtp] [options...]

set -e -u

if [[ -z ${MUTTERER_LIBS+_} || -z ${MUTTERER_SYSTEM_PRESETS+_} ]]; then
    dir=$(dirname "$(readlink -f "$0")")
fi

export MUTTERER_LIBS="${MUTTERER_LIBS-$dir/lib}"
export MUTTERER_SYSTEM_PRESETS="${MUTTERER_SYSTEM_PRESETS-$dir/presets}"

. "$MUTTERER_LIBS/m_common"
. "$MUTTERER_LIBS/m_installer"

case "${1-}" in
    install) make_config;;
    mutt)    shift; make_config_if_updated; mutt "$@";;
    imap)    shift; make_config_if_updated; offlineimap "$@";;
    smtp)    shift; make_config_if_updated; msmtp "$@";;
    *)       make_config_if_updated; mutt "$@";;
esac
