#!/bin/bash

# keys_for_account account_id
keys_for_account()
{
    printf '%s\n' "${!settings[@]}" | grep "^accounts\.$1\."
}

# all_accounts_except [accounts...]
all_accounts_except()
{
    comm -23 <(printf '%s\n' "${!accounts[@]}" | sort) \
             <(printf '%s\n' "$@" | sort -u)
}

# escape_spaces text : escape spaces with <quote-char> as required by
# interactive mutt commands
escape_spaces()
{
    sed 's/ /<quote-char><space>/g' <<< "$1"
}
