#!/bin/bash

# keys_for_account account_id
keys_for_account()
{
    local IFS=$'\n'
    printf '%s' "${!settings[*]}" | grep "^accounts\.$1\."
}

# all_accounts_except [accounts...]
all_accounts_except()
{
    local IFS=$'\n'
    printf '%s\n%s' "${!accounts[*]}" "$(sort <<<"$*" | uniq)" |
    sort | uniq -u
}
