#!/bin/bash

# --- Mutterer generic common elements ---

set -e -u

nl='
'

: ${DEBUG=off}
: ${TOP_PID=$$}

# Common regexes:
r_word='[a-zA-Z_-][a-zA-Z0-9_-]*'

error()
{
    printf 'Error: %s\n' "$*" 1>&2
    kill "$TOP_PID"
    exit 1
}

# debug()
# {
#     if [[ "$DEBUG" == on ]]; then printf '%s\n' "$*"; fi
# }
