#!/bin/bash

# --- Mutterer common elements ---

set -e -u

. "$MUTTERER_LIBS/common"

: ${MUTTERERRC=~/.muttererrc}
: ${MUTTERER_DIR=~/.mutterer}
configs_dir=$MUTTERER_DIR/configs

: ${MUTTRC=~/.muttrc}
: ${MUTTRC2=~/.mutt/muttrc}
: ${OFFLINEIMAPRC=~/.offlineimaprc}
: ${OFFLINEIMAPLOCK=~/.offlineimap/lock}
: ${MSMTPRC=~/.msmtprc}
