#!/bin/bash

# --- Mutterer Installing ---

set -e -u

. "$MUTTERER_LIBS/m_parser"

# _install : CALL WITH OFFLINEIMAP LOCKED
_install()
{
    cp "$configs_dir"/muttrc "$MUTTRC"
    cp "$configs_dir"/offlineimaprc "$OFFLINEIMAPRC"
    cp "$configs_dir"/msmtprc "$MSMTPRC"
}

_make_script()
{
    mkdir -p "$configs_dir"
    cat "$MUTTERER_LIBS/bash_script_base" > "$configs_dir/script.bash"
    parse_file "$MUTTERERRC" >> "$configs_dir/script.bash"
}

make_config()
{
    mkdir -p "$(dirname "$OFFLINEIMAPLOCK")"
    {
        flock -n 9 || error "Couldn't capture offlineimap lock. Exiting."
        _make_script
        export configs_dir
        "$MUTTERER_LIBS/bash_script_wrapper" \
            "$MUTTERER_LIBS/m_installer_run_script_and_print"
        _install
    } 9>"$OFFLINEIMAPLOCK"
}

updated()
{
    [[ "$MUTTERERRC" -nt "$MUTTRC" ]] ||
    [[ "$MUTTERERRC" -nt "$OFFLINEIMAPRC" ]] ||
    [[ "$MUTTERERRC" -nt "$MSMTPRC" ]]
}

make_config_if_updated()
{
    if updated; then
        echo 'Mutterer: updating config...' 1>&2
        make_config
    fi
}
